#!/bin/sh
hyprctl activewindow -j | jq --raw-output .title | sed 's/\(.\{15\}\).*/\1.../'
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print substr($3, 1, 58) "..."}'
