#!/bin/bash

## Get battery info
get_volume() {
	pamixer --get-volume | tr -d \%,
}

main() {
	mute_status=$(pactl get-sink-mute @DEFAULT_SINK@)
	if [[ "$mute_status" == "Mute: yes" || "$mute_status" == "Mute: sì" ]]; then
		echo ""
	else
		echo "$last_icon" 
		current_volume=$(get_volume)
		if [[ "$current_volume" != "$old_volume" ]]; then
				old_volume="$current_volume"
				if [[ ($current_volume -gt 65) ]]; then
					last_icon=""
					echo "$last_icon"
				elif [[ ($current_volume -lt 65) && (($current_volume -gt 35) || ($current_volume -eq 35)) || ($current_volume -eq 65) ]]; then
					last_icon=""
					echo "$last_icon"
				fi
				elif [[ ($current_volume -lt 35) && (($current_volume -gt 0) || ($current_volume -eq 0)) ]]; then
					last_icon=""
					echo "$last_icon"
				fi
		fi
}

old_volume="-1"
last_icon=""


while true; do
if [[ $1 == '--icon' ]]; then
	main
elif [[ $1 == '--perc' ]]; then
		current_volume=$(get_volume)
		if [[ "$current_volume" != "$old_volume" ]]; then
			echo "$current_volume"
			old_volume="$current_volume"
		fi
fi		
if [[ $1 == 'down' ]]; then
	pamixer -i 1
	break
elif [[ $1 == 'up' ]]; then
	pamixer -d 1
	break
fi
done

